### ISSUE TITLE
ightning_base.py", line 59, in __init__: AttributeError: can't set attribute

### ISSUE THREAD

**Issue by dbl001** [allenai/comet-atomic-2020#17]
I got this error $bash ./run.sh     : AttributeError: can't set attribute
```
% ipython
Python 3.8.13 (default, Mar 28 2022, 06:16:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.2.0 -- An enhanced Interactive Python. Type '?' for help.
In [2]: import pytorch_lightning
In [3]: print(pytorch_lightning.__version__)
1.6.3

In [4]: import torch
In [5]: print(torch.__version__)
1.10.1

% bash ./run.sh           
Traceback (most recent call last):
  File "finetune.py", line 441, in <module>
    main(args)
  File "finetune.py", line 330, in main
    model: SummarizationModule = SummarizationModule(args)
  File "finetune.py", line 68, in __init__
    super().__init__(hparams, num_labels=None, mode=self.mode, **kwargs)
  File "/Users/davidlaxer/comet-atomic-2020/models/comet_atomic2020_bart/lightning_base.py", line 59, in __init__
    self.hparams = hparams
  File "/Users/davidlaxer/tensorflow-metal/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1225, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute

```

https://github.com/PyTorchLightning/pytorch-lightning/issues/7443

**Comment by dbl001** [comment]
I was hoping that 'comet' would run with torch 1.13 (which has the new GPU backend support: 'mps'.)
./run.sh does work in a new conda virtual environment with all the packages specified in requirements.txt.

**Comment by dbl001** [comment]
In lightning_base.py had to use 
```
 self.save_hyperparameters(hparams)
```
and comment out:
```
self.hparams = hparams
```

**Comment by iaamlele** [comment]
Also, in requirements.txt:
torch==1.8.1
